# Measure center-of-mass distance between two atom selections 
# author: Yuhang Wang
# date: 06/11/2015
#
# note: since Tcl doesn't allow input argument to contain spaces
#     the only way to work around is to use input files that
#     contains an input string (with any number of spaces)
#
# usage: vmd -dispdev text -e get_com_distance.tcl \
#           -args PSF PDB DCD \
#                 OUTPUT_DATA \
#                 FILE_SELECTION_1 \
#                 FILE_SELECTION_2
# note: OUTPUT_DATA is the file that will contain all the data generated by this script
#
###################################################################################

puts "'------------'"
set ccc 0
set in_psf [lindex $argv $ccc]
puts "in psf  $in_psf"
incr ccc
set in_pdb [lindex $argv $ccc]
puts $in_pdb 

incr ccc
set in_dcd [lindex $argv $ccc]

incr ccc
# The name of the file that will contain all the output data
# generated by this script.
set output_file_name [lindex $argv $ccc]

incr ccc
# a file containing an atom selection string for alignment
set file_selection_1 [lindex $argv $ccc]

incr ccc
# a file containing an atom selection string for the RMSD measurement
set file_selection_2 [lindex $argv $ccc]

#=================================================================
proc get_selection_str {in_file_name} {
  ## Read a file and use its content a the returning string 
  set IN [open $in_file_name r]
  set my_str [read $IN]
  close $IN
  return $my_str
}

proc load {in_psf in_pdb in_dcd} {
  ## load psf, pdb and dcd 
  puts "=============================================================="
  puts "--------------------------------------------------------------"
  puts "     Loading $in_psf"
  puts "     Loading $in_pdb"
  puts "     Loading $in_dcd"
  puts "--------------------------------------------------------------"
  set molId [mol new $in_psf]
  mol addfile $in_pdb molid $molId 
 
  mol addfile $in_dcd waitfor all molid $molId 
  return $molId
}

proc get_com_distance {molId str_selection_1 str_selection_2} {
  # measure distance between two atom selections 
  puts "--------------------------------------------------------------"
  puts "  Measure distance between two atom selections"
  puts "  (1):  $str_selection_1"
  puts "  (2):  $str_selection_2"
  puts "--------------------------------------------------------------"
  
  set list_com_distances {}
  set sel1 [atomselect $molId $str_selection_1]
  set sel2 [atomselect $molId $str_selection_2]
  set totalNumFrames [molinfo $molId get numframes]

  for {set i 0} {$i < $totalNumFrames} {incr i} {
    $sel1 frame $i
    $sel2 frame $i
    set coord1 [measure center $sel1 weight mass]
    set coord2 [measure center $sel2 weight mass]
    set distance [veclength [vecsub $coord1 $coord2]]
    lappend list_com_distances $distance
  }
  $sel1 delete
  $sel2 delete
  return $list_com_distances
}

proc write_output {in_list output_file_name} {
  puts "--------------------------------------------------------------"
  puts "  Output file: "
  puts "  $output_file_name"
  puts "--------------------------------------------------------------"
  set OUT [open $output_file_name w]
  foreach data $in_list {
      puts $OUT $data
  }
  close $OUT
}

#---------------------------------------------------------------------------
#                     MAIN 
#---------------------------------------------------------------------------

## get atom selection string for alignment
set str_selection_1 [get_selection_str $file_selection_1]

## get atom selection string for RMSD calculation
set str_selection_2 [get_selection_str $file_selection_2]

set molId [load $in_psf $in_pdb $in_dcd]
set list_com_distances [get_com_distance $molId $str_selection_2]
write_output $list_com_distances $output_file_name
mol delete $molId 

puts "============================================================="
puts "                         DONE!                               "
puts "  Output: $output_file_name                                  "
puts "============================================================="
exit
